/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatbb;

import static chatbb.Usuario1.txtConMensaje;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author GDB beto
 */
public class Usuario2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Usuario2
     */
    private Encriptamiento encriptamiento= new Encriptamiento();
    public Usuario2() {
        initComponents();
        txtMensajeU2.requestFocus();
        verMensajeNuevos();
    }
    
    public void verMensajeNuevos(){
        Timer timer= new Timer();
        TimerTask task = new TimerTask() {
            @Override
            public void run() {              
                if(encriptamiento.getStatusMsjUsuario1()){
                    txtConMensaje.setText(txtConMensaje.getText()+"Usuario 1: "+encriptamiento.getMensaje()+"\n");
                    encriptamiento.setStatusMsjUsuario1(false);
                    txtProceso.setText(txtProceso.getText()+
                            "----------------------------------------------------------------\n"
                            + encriptamiento.getMensajeEncriptado()+"\n");
                    formatColor();
                }
     
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        };       
        timer.schedule(task, 50, 1000); 
    }

    
    public void formatColor(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMensajeU2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConMensaje = new javax.swing.JEditorPane();
        btnEnviar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProceso = new javax.swing.JTextArea();

        setClosable(true);
        setToolTipText("");

        txtMensajeU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensajeU2ActionPerformed(evt);
            }
        });

        txtConMensaje.setEditable(false);
        txtConMensaje.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(txtConMensaje);

        btnEnviar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtProceso.setEditable(false);
        txtProceso.setBackground(new java.awt.Color(250, 250, 250));
        txtProceso.setColumns(20);
        txtProceso.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtProceso.setRows(5);
        jScrollPane2.setViewportView(txtProceso);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMensajeU2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMensajeU2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
       enviar();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtMensajeU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensajeU2ActionPerformed
        // TODO add your handling code here:
        enviar();
    }//GEN-LAST:event_txtMensajeU2ActionPerformed

    public void enviar(){
         if (!txtMensajeU2.getText().equals("")) {
            encriptamiento.setMensaje(txtMensajeU2.getText());
            txtConMensaje.setText(txtConMensaje.getText() + "            Tu: " + txtMensajeU2.getText() + "\n");
            txtMensajeU2.setText("");
            encriptamiento.setStatusMsjUsuario2(true);
            //Usuario2.txtMensajeU2.setText(txtMensajeU1.getText());
            formatColor();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JEditorPane txtConMensaje;
    public static javax.swing.JTextField txtMensajeU2;
    public static javax.swing.JTextArea txtProceso;
    // End of variables declaration//GEN-END:variables
}
