/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatbb;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author GDB beto
 */
public class Usuario1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Usuario1
     */
    private Encriptamiento encriptamiento= new Encriptamiento();
    public Usuario1() {
        initComponents();
        txtMensajeU1.requestFocus();
        verMensajeNuevos();
        
    }

    public  void verMensajeNuevos(){
        Timer timer= new Timer();
        TimerTask task = new TimerTask() {
            @Override
            public void run() {          
                if(encriptamiento.getStatusMsjUsuario2()){
                    txtConMensaje.setText(txtConMensaje.getText()+"Usuario 1: "+encriptamiento.getMensaje()+"\n");
                    encriptamiento.setStatusMsjUsuario2(false);
                    txtProceso.setText(txtProceso.getText()+
                            "----------------------------------------------------------------\n"
                            + encriptamiento.getMensajeEncriptado()+"\n");
                
                }
     
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        };       
        timer.schedule(task, 50, 1000); 
    }

    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMensajeU1 = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConMensaje = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProceso = new javax.swing.JTextArea();

        setClosable(true);

        txtMensajeU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensajeU1ActionPerformed(evt);
            }
        });

        btnEnviar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtConMensaje.setEditable(false);
        txtConMensaje.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(txtConMensaje);

        txtProceso.setEditable(false);
        txtProceso.setBackground(new java.awt.Color(250, 250, 250));
        txtProceso.setColumns(20);
        txtProceso.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtProceso.setRows(5);
        jScrollPane2.setViewportView(txtProceso);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtMensajeU1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                        .addComponent(jScrollPane1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMensajeU1)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
       enviar();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtMensajeU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensajeU1ActionPerformed
        // TODO add your handling code here:
        enviar();
    }//GEN-LAST:event_txtMensajeU1ActionPerformed

    public void enviar(){
        if (!txtMensajeU1.getText().equals("")) {
            encriptamiento.setMensaje(txtMensajeU1.getText());
            txtConMensaje.setText(txtConMensaje.getText() + "            Tu: " + txtMensajeU1.getText() + "\n");
            txtMensajeU1.setText("");
            encriptamiento.setStatusMsjUsuario1(true);
          
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JEditorPane txtConMensaje;
    private javax.swing.JTextField txtMensajeU1;
    public static javax.swing.JTextArea txtProceso;
    // End of variables declaration//GEN-END:variables
}
